### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by mathrick** [mathrick/godot-asset-uploader#5]
Will probably go with GitHub Actions, shitty as they are, since it's built into GH.

Checklist:
* [x] Unit tests run for every commit
* [ ] Build infra for wheels
* [ ] Build infra for Windows binaries (needs #6)
* [ ] Bundling and testing of external binaries (ie. `hg` fallback, see #4)
* [ ] Workflow for tagging a release
* [ ] Workflow for PyPI uploads
